- name: "Create backup paths file for {{ job.key }}"
  copy:
    content: |
      {{ ansible_managed }}
      {% for include in job.value.paths %}
      {{ include }}
      {% endfor %}
    dest: "{{ backups_borg_config_dir }}/{{ job.key }}.paths.txt"
  when: job.value.paths is defined

- name: "Create backup excludes file for {{ job.key }}"
  copy:
    content: |
      {{ ansible_managed }}
      {% for exclude in job.value.get('excludes', []) %}
      {{ exclude }}
      {% endfor %}
    dest: "{{ backups_borg_config_dir }}/{{ job.key }}.excludes.txt"


- name: "Create service files for {{ job.key }} backup"
  include_role:
    name: common
    tasks_from: create_service
  vars:
    service_name: "backup-{{ job.key }}"
    service_schedule: "{{ job.value.calendar | default(omit) }}"
    service_random_delay: "{{ job.value.random_delay | default(omit) }}"
    service_script: >-
      {{ lookup('template', 'machine_backup.bash.j2') }}
