- name: "Create backup paths file for {{ job.key }}"
  copy:
    content: |
      {{ ansible_managed }}
      {% for include in job.value.paths %}
      {{ include }}
      {% endfor %}
    dest: "{{ backups_borg_config_dir }}/{{ job.key }}.paths.txt"
  when: job.value.paths is defined

- name: "Create backup excludes file for {{ job.key }}"
  copy:
    content: |
      {{ ansible_managed }}
      {% for exclude in job.value.get('excludes', []) %}
      {{ exclude }}
      {% endfor %}
    dest: "{{ backups_borg_config_dir }}/{{ job.key }}.excludes.txt"


- name: "Create service files for {{ job.key }} backup"
  include_role:
    name: common
    tasks_from: create_service
  vars:
    service_name: "backup-{{ job.key }}"
    service_schedule: "{{ job.value.calendar | default(omit) }}"
    service_script: |
      logmsg() {
        # get from stdin if no argument
          if [ -z "$1" ]; then
            msg=""
            while IFS= read -r line; do
                printf '%s\n' "$line"
                msg+="$line"$'\n'
            done
            msg="${msg//\\n/$'\n'}"
        else
          echo "$1"
          msg="$1"
        fi

        if [ -z "$WEBHOOK_URL" ]; then
          return
        fi

        curl -X POST -H 'Content-type: application/json' -d "$(jq -n --arg m "$msg" '{content: $m}')" $WEBHOOK_URL
      }

      if [ -f "{{ backups_secrets_file }}" ]; then
        source "{{ backups_secrets_file }}"
      fi

      ssh_key=$(find "{{ ansible_facts.user_dir }}/.ssh/borg_key" "{{ ansible_facts.user_dir }}/.ssh/id_rsa" "{{ ansible_facts.user_dir }}/.ssh/id_ed25519" | head -n 1)

      if [ -z "$ssh_key" ]; then
        logmsg "No SSH key found for borg backup!"
        exit 1
      fi

      export BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes
      export BORG_RELOCATED_REPO_ACCESS_IS_OK=yes
      export BORG_REPO="{{ job.value.repository }}"
      export BORG_KEYS_DIR={{ ansible_facts.user_dir }}/.config/borg/keys
      export BORG_RSH="ssh -i $ssh_key -o StrictHostKeyChecking=no"

      logmsg "Backup job \"{{ job.key }}\" started on {{ ansible_hostname }}."

      {% if job.value.prepare_script is defined %}
      (
        {{ job.value.prepare_script }}
      ) 2>&1 | logmsg
      {% endif %}

      # no pipefail here is important, we want to capture find's output even
      # on exit 1s
      find $(cat "{{ backups_borg_config_dir }}/{{ job.key }}.paths.txt") 2>/dev/null | borg create --stats --paths-from-stdin --exclude-from="{{ backups_borg_config_dir }}/{{ job.key }}.excludes.txt" ::{{ job.value.archive }} 2>&1 | logmsg

      {% if job.value.cleanup_script is defined %}
      (
        {{ job.value.cleanup_script }}
      ) 2>&1 | logmsg
      {% endif %}
