- name: Ensure borg is installed
  package:
    name: borgbackup
    state: present
  when: ansible_facts.user_id == 'root'

- name: Use root borg config directory
  set_fact:
    backups_borg_config_dir: "{{ backups_borg_config_dir_root }}"
  when:
    - ansible_facts.user_id == 'root'
    - backups_borg_config_dir is not defined

- name: Use user borg config directory
  set_fact:
    backups_borg_config_dir: "{{ backups_borg_config_dir_user }}"
  when:
    - ansible_facts.user_id != 'root'
    - backups_borg_config_dir is not defined

- name: Ensure borg config directory exists
  include_role:
    name: common
    tasks_from: create_directory
  vars:
    path: "{{ backups_borg_config_dir }}"

- set_fact:
    borg_admin_user: >-
      {{ ansible_facts.env.SUDO_USER or ansible_facts.user_id }}

- user:
    name: "{{ borg_admin_user }}"
  register: backup_user_info

- set_fact:
    ansible_facts:
      user_dir: "{{ backup_user_info.home }}"

- name: Check if env file exists
  stat:
    path: "{{ backups_secrets_file }}"
  register: env_file

- name: Enforce env file permissions
  file:
    path: "{{ backups_secrets_file }}"
    owner: "{{ borg_admin_user }}"
    group: "{{ borg_admin_user }}"
    mode: u=rw,g=,o=
  when: env_file.stat.exists

- name: Import backup configuration task for each job
  include_role:
    name: "{{ role_name }}"
    tasks_from: for_job
  loop: "{{ backups_jobs | dict2items }}"
  loop_control:
    loop_var: job
    label: "{{ job.key }}"

- name: Create backup housekeeping script
  include_role:
    name: common
    tasks_from: create_service
  vars:
    service_name: backup-repos-housekeeping
    service_scope: user
    service_user: "{{ borg_admin_user }}"
    service_schedule: "{{ backup_repos_housekeeping_schedule }}"
    service_script: >-
      {{ lookup('template', 'user_repos_housekeeping.bash.j2') }}
  when: backups_repos | length > 0
