- hosts: all
  become: true

  tasks:
    - include_tasks:
        file: "tasks/server/{{ task }}.yml"
        apply:
          tags:
            - server
            - "{{ task }}"
      loop:
        - hostname
        - pkg-mgr-conf
        - packages
        - periodic-upgrade
        - skeleton
        - users
        - caddy
      loop_control:
        loop_var: task
      tags:
        - always

  handlers:
    - name: systemd reload
      systemd:
        daemon_reload: true
    - name: caddy reload
      systemd:
        name: caddy
        state: restarted
