- hosts: all
  become: true

  tasks:
    - include_tasks:
        file: "tasks/server/{{ task }}.yml"
        apply:
          tags:
            - server
            - "{{ task }}"
      loop: "{{ tasks_list_base + tasks_list }}"
      loop_control:
        loop_var: task
      tags:
        - always

  handlers:
    - name: systemd reload
      systemd:
        daemon_reload: true
    - name: caddy reload
      include_tasks: tasks/server/caddy_reload.yml
    - name: cockpit reload
      systemd:
        name: cockpit.socket
        state: restarted
    - name: wsdd restart
      systemd:
        name: wsdd
        state: restarted
    - name: dnsmasq restart
      systemd:
        name: dnsmasq
        state: restarted
