- hosts: all
  become: true

  tasks:
    - include_role:
        name: common
        tasks_from: delete_service
        apply:
          tags:
            - clean
      vars:
        service_name: "{{ item.name }}"
        service_timer: "{{ item.timer | default(False) }}"
      loop:
        - name: backup_machine
          timer: true
        - name: smart_check
      tags: always
    - include_tasks:
        file: "tasks/server/{{ task }}.yml"
        apply:
          tags:
            - server
            - "{{ task }}"
      loop: "{{ server_tasks_base + server_tasks }}"
      loop_control:
        loop_var: task
      tags: always
      when: task not in server_tasks_disabled
    - include_role:
        name: "{{ role }}"
        apply:
          tags:
            - "{{ role }}"
      tags: always
      loop:
        - containers
        - backups
        - disk_use_report
        - smart
        - caddy
        - alloy
      loop_control:
        loop_var: role

    # - name: Install Prometheus Node Exporter
    #   include_role:
    #     name: prometheus.prometheus.node_exporter
    #     apply:
    #       tags:
    #         - server
    #         - node_exporter
    #   vars:
    #     node_exporter_web_listen_address: "localhost:9100"
    #   tags:
    #     - always

  handlers:
    - name: cockpit reload
      systemd:
        name: cockpit.socket
        state: restarted
    - name: wsdd restart
      systemd:
        name: wsdd
        state: restarted
    - name: dnsmasq restart
      systemd:
        name: dnsmasq
        state: restarted
    - name: promtail restart
      systemd:
        name: promtail
        state: restarted
    - name: tunnels restart
      systemd:
        name: tunnels
        state: restarted
    - name: fail2ban restart
      systemd:
        name: fail2ban
        state: restarted
