- hosts: all
  become: true

  tasks:
    - include_tasks:
        file: "tasks/server/{{ task }}.yml"
        apply:
          tags:
            - server
            - "{{ task }}"
      loop: "{{ server_tasks_base + server_tasks }}"
      loop_control:
        loop_var: task
      tags: always
      when: task not in server_tasks_disabled
    - include_role:
        name: "{{ item }}"
        apply:
          tags:
            - "{{ item }}"
      tags: always
      loop:
        - backups

    # - name: Install Prometheus Node Exporter
    #   include_role:
    #     name: prometheus.prometheus.node_exporter
    #     apply:
    #       tags:
    #         - server
    #         - node_exporter
    #   vars:
    #     node_exporter_web_listen_address: "localhost:9100"
    #   tags:
    #     - always

  handlers:
    - name: systemd reload
      systemd:
        daemon_reload: true
    - name: caddy restart
      include_tasks: tasks/handlers/caddy_restart.yml
    - name: cockpit reload
      systemd:
        name: cockpit.socket
        state: restarted
    - name: wsdd restart
      systemd:
        name: wsdd
        state: restarted
    - name: dnsmasq restart
      systemd:
        name: dnsmasq
        state: restarted
    - name: promtail restart
      systemd:
        name: promtail
        state: restarted
    - name: tunnels restart
      systemd:
        name: tunnels
        state: restarted
    - name: fail2ban restart
      systemd:
        name: fail2ban
        state: restarted
