- hosts: all
  become: true

  tasks:
    - include_tasks:
        file: "tasks/server/{{ task }}.yml"
        apply:
          tags:
            - server
            - "{{ task }}"
      loop:
        # Core config
        - hostname
        - selinux
        - timezone

        # Packages
        - pkg-mgr-conf
        - packages
        - periodic-upgrade

        # Users
        - skeleton
        - cgroups
        - containers
        - users
        - paths

        # Services
        - caddy
        - cockpit
      loop_control:
        loop_var: task
      tags:
        - always

  handlers:
    - name: systemd reload
      systemd:
        daemon_reload: true
    - name: caddy reload
      include_tasks: tasks/server/caddy_reload.yml
    - name: cockpit reload
      systemd:
        name: cockpit.socket
        state: restarted
