- hosts: all
  become: true
  become_user: tina

  tasks:
    - include_tasks:
        file: "tasks/user/{{ task }}.yml"
        apply:
          tags:
            - user
            - "{{ task }}"
      loop:
        - dotfiles
        # - websites
        - containers
        - compose_services
        - repositories
        - services
        - mounts
        - prometheus
      loop_control:
        loop_var: task
      tags:
        - always

  handlers:
    - name: systemd reload user-mode
      systemd:
        daemon_reload: true
        scope: user
    - name: prometheus restart
      systemd:
        name: prometheus
        state: restarted
        scope: user
