- hosts: all
  become: true
  become_user: tina

  tasks:
    - include_tasks:
        file: "tasks/user/{{ task }}.yml"
        apply:
          tags:
            - user
            - "{{ task }}"
      loop: "{{ user_tasks_base + user_tasks }}"
      loop_control:
        loop_var: task
      tags:
        - always
    - include_role:
        name: "{{ role }}"
        apply:
          tags: "{{ role }}"
      tags: always
      loop:
        - containers
        - loki
      loop_control:
        loop_var: role

  handlers:
    - name: systemd reload
      systemd:
        daemon_reload: true
    - name: systemd user reload
      systemd:
        daemon_reload: true
        scope: user
    - name: prometheus restart
      systemd:
        name: prometheus
        state: restarted
        scope: user
