caddy_service: caddy

# If set, Caddy will run as this user and group. The user and group must already
# exist on the system.
# If not set, it will use the package default, which is usually "caddy".
caddy_user: false

caddy_access_log: /var/log/caddy/access.log

caddy_logs_outputs: {}
# name: output

caddy_https: true

caddy_email: false

caddy_opentelemetry: false

caddy_entries: []
# domain: example.com
# file: example (optional, if true will be added as a separate file in
#       Caddyfile.d instead of the main Caddyfile)
# partial: false (optional, if true the whole file will not be overwritten
# root: /srv/www/example (optional)
# robots: false (optional, if false will respond to /robots.txt to disable
#         crawlers)
# browser: true (optional, enable filebrowser)
# reverses: []
#  to: 8080
#  path: /app (optional, if not set will reverse all paths)
#  redir_slash: false (optional, if false will not redirect /app to /app/)
#  remove_path: true (optional, if true will strip the path from the request)
#  extra: "" (optional, extra Caddy directives to add in this entry)

# Appended at the bottom of the global Caddyfile
caddy_extra: ""

# Appended in the global options block of the Caddyfile
caddy_global_extra: ""

# For these errors, respond with /srv/www/errors/{error}.html
# The file must exist, it will not be generated by Caddy
caddy_error_handlers: []
# - 502

caddy_disable_common_loggers: false
