{
 "title": "Dijiang Caddy room",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {}
   },
   { "name": "job", "query": "caddy" },
   {
    "name": "is_bot",
    "label": "Bot requests",
    "query": "Include : true|false, Only : true, Exclude : false"
   },
   {
    "name": "status_filter",
    "label": "Status",
    "query": "All requests : .*, 2xx / 3xx : [23].., 4xx : 4.., 5xx : 5.."
   },
   {
    "name": "query",
    "query": "{job=\"$job\"\\, host=~\"${host:pipe}\"\\, is_bot=~\"$is_bot\"} | status=~\"$status_filter\""
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Bots parity",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(is_bot) (count_over_time({job=~\"$job\", host=~\"${host:pipe}\", is_bot=~\"true|false\"} [$__range]))",
     "legendFormat": "{{is_bot}}"
    }
   ]
  },
  { "title": "100 / 200 / 300", "type": "library-panel-ref", "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 } },
  { "title": "400", "type": "library-panel-ref", "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 } },
  { "title": "500", "type": "library-panel-ref", "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 } },
  {
   "title": "Requests per domain",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by(host) (count_over_time($query [$__range])))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Requests per path",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(50, sum by(path) (count_over_time($query | json uri | __error__=\"\" | line_format \"{{.uri}}\" | regexp \"(?P<uri>[^?#]*)\" | label_format path=\"{{.host}}{{.uri}}\" [$__range])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by(host) (rate($query [$__interval]) * 60))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Access logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "direction": "backward",
     "expr": "$query | line_format `{{.client_ip}} {{.method}} {{.status}} {{.host}}{{.uri}} {{ .msg}} {{.duration}}s {{.size}}B`"
    }
   ]
  }
 ]
}