server_tasks_base:
  # Core config
  - hostname
  - selinux
  - timezone
  - hosts

  # Packages
  - pkg-mgr-conf
  - packages
  - periodic-upgrade
  - fzf

  # Users
  - cgroups
  - containers
  - users
  - paths

  # Services
  - firewall
  - caddy
  - cockpit
  - users_fstab
  - promtail

server_tasks: []

user_tasks_base:
  - dotfiles
  # - websites
  - containers
  - compose_services
  - repositories
  - mounts
  - services

user_tasks: []

loopback_ip: 127.0.0.1
podman_host_loopback_ip: 10.0.2.2
podman_host_address: host.containers.internal

caddy_admin_port: 2019
cockpit_port: 9090
flood_port: 3000
grafana_port: 3003
graylog_port: 9000
infra_webui_port: 10001
jellyfin_port: 8096
loki_port: 3100
outline_port: 3002
prometheus_port: 9091
prometheus_node_exporter_port: 9100
promtail_port: 9080
prowlarr_port: 9696
qbittorrent_webui_port: 8080
radarr_port: 7878
readarr_port: 8787
sonarr_port: 8989
uptime_kuma_port: 3001

graylog_version: 5.2.2
flood_url_root: /flood
user_apps_dir: "{{ ansible_user_dir }}/.local/opt"

linuxserver_env:
  PUID: 0
  PGID: 0

selinux_state: disabled

packages_base:
  - caddy
  - cockpit
  - cockpit-file-sharing
  - cockpit-navigator
  - cockpit-pcp
  - cockpit-podman
  - cockpit-storaged
  - dhcpdump
  - ffmpeg
  # - fzf
  - git
  - htop
  - httpie
  # - megatools
  - ncdu
  - net-tools
  - nfs-utils
  - nmap
  - podman
  - promtail
  - screen
  - sqlite
  - sshfs
  - tree
  - util-linux-user
  - vim
  - wireguard-tools
  - zsh
  - zsh-syntax-highlighting

packages: []

packages_remove:
  - crontabs
  - haveged
  - udisks2-iscsi

# Override how to install packages for a given distro
packages_by_distro:
  Rocky:
    "9":
      # Not in EPEL repos for RHEL 9 (yet?)
      # - name: zsh-syntax-highlighting
      #   url: "http://rpmfind.net/linux/epel/8/Everything/{{ ansible_architecture }}/Packages/z/zsh-syntax-highlighting-0.7.1-1.el8.noarch.rpm"
      - name: fzf
        url: "https://www.rpmfind.net/linux/fedora/linux/updates/38/Everything/{{ ansible_architecture }}/Packages/f/fzf-0.42.0-1.fc38.{{ ansible_architecture }}.rpm"
      - name: caddy
        copr: "@caddy/caddy"
      - name: megatools
        url: https://www.rpmfind.net/linux/fedora/linux/releases/38/Everything/{{ ansible_architecture }}/os/Packages/m/megatools-1.11.1-1.fc38.{{ ansible_architecture }}.rpm
      - name: filebeat
        url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.11.3-x86_64.rpm
      # - name: centos-release-kmods
      #   url: https://cbs.centos.org/kojifiles/packages/centos-release-kmods/9/3.el9s/noarch/centos-release-kmods-9-3.el9s.noarch.rpm
      - name: promtail
        url: https://github.com/grafana/loki/releases/download/v2.8.11/promtail-2.8.11.x86_64.rpm


upgrade_commands:
  dnf:
    - systemctl restart chronyd
    - dnf -y upgrade --refresh
upgrade_schedule: "weekly"
upgrade_then_reboot: true
upgrade_service_name: upgrade-and-restart


pkgmgr_default_yes: true
pkgmgr_install_weak_deps: true
pkgmgr_dnf_deltarpm: true
pkgmgr_dnf_metadata_expire: 604800 # 1 week


users: []
users_admins: []
skel: []


hostname: null

timezone: "Europe/Paris"


http_domain: "{{ ansible_host }}"


caddy_https: true
caddy_email: null
caddy_entries: []
caddy_service: caddy
caddy_user: root
caddy_prometheus: false

cockpit_url_root: /cockpit
cockpit_allow_unencrypted: "{{ not caddy_https }}"
cockpit_login_to: true


user_mounts: []

containers: {}
containers_registries:
  - docker.io

quadlets: {}

compose_services: []
compose_dir: "{{ user_apps_dir }}"

repositories: []
repositories_dir: "{{ user_apps_dir }}"


user_services: {}

python_setup: |-
  python -m venv .venv
  source .venv/bin/activate
  pip install -r requirements.txt

bash_setup: |-
  export PATH={{ ansible_user_dir }}/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin

compose_setup: |-
  {{ bash_setup }}
  podman-compose stop
  rm -rfv {{ ansible_user_dir }}/.local/share/containers/storage/overlay/*/merged
  podman-compose down --remove-orphans
  podman-compose build --pull
  podman-compose up
