loopback_ip: 127.0.0.1
podman_host_loopback_ip: 10.0.2.2
podman_host_address: host.containers.internal

python_setup: |-
  python -m venv .venv
  source .venv/bin/activate
  pip install -r requirements.txt

bash_setup: |-
  export PATH={{ ansible_user_dir }}/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin

compose_setup: |-
  {{ bash_setup }}
  podman-compose stop
  rm -rfv {{ ansible_user_dir }}/.local/share/containers/storage/overlay/*/merged
  podman-compose down --remove-orphans
  podman-compose build --pull
  podman-compose up
