loopback_ip: 127.0.0.1
podman_host_loopback_ip: 10.0.2.2
podman_host_address: host.containers.internal

python_setup: |-
  [ -d .venv ] || python -m venv .venv
  source .venv/bin/activate
  pip install -r requirements.txt

bash_setup: |-
  export PATH={{ ansible_facts.user_dir }}/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin

compose_setup: |-
  {{ bash_setup }}
  podman-compose stop
  rm -rfv {{ ansible_facts.user_dir }}/.local/share/containers/storage/overlay/*/merged
  podman-compose down --remove-orphans
  podman-compose build --pull
  podman-compose up

sssimp_setup: |-
  {{ bash_setup }}
  [ -d .venv ] || python -m venv .venv
  ./.venv/bin/pip install sssimp
  ./.venv/bin/sssimp

linuxserver_env:
  # Since we run containers as the current user, we need to run as root inside
  # the container, as root in container = current user outside the container
  # with Podman
  PUID: 0
  PGID: 0
  UMASK: 002

sus_http_fails:
  - wp-login.php
  - wp-admin
  - wordpress
  - new
  - old
  - wp

  - administrator
  - admin
  - login
  - register
  - user/login
  - user/register
  - backup

  - .git
  - .aws
  - .docker
  - .ssh
  - _nuxt
  - dist
  - vendor
  - .vite
  - build-manifest.json
  - account
  - health
  - manifest.webmanifest
  - swagger.json
  - __env.js
  - app-config.json
  - openapi.json
  - settings
  - runtime-config.js
  - config
  - jwks.json
  - laravel.log
  - settings.*
  - config.*
  - init.json
  - application.properties

  - .env
  - .env.*
  - env
  - sa.json
  - service-account.json
  - google-service-account.json
  - serviceAccountKey.json
  - firebase-service-account.json
  - credentials.json
  - gcp-credentials.json
  - secrets.*
  - application.*
  - key.*
  - .npmrc
  - .pypirc
  - settings.*
