server_tasks_base:
  # Core config
  - hostname
  - selinux
  - timezone
  - hosts

  # Packages
  - pkg-mgr-conf
  - packages
  - fuse
  # - periodic-upgrade
  - fzf

  # Users
  - cgroups
  - containers
  - users
  - paths

  # Services
  - firewall
  - fail2ban
  - login_hook
  - caddy
  - cockpit
  - users_fstab
  # - promtail
  # - tunnels
  # - healthcheck

server_tasks: []

user_tasks_base:
  - dotfiles
  # - websites
  - containers
  - compose_services
  - repositories
  - mounts
  - services
  - minecraft

user_tasks: []

flood_url_root: /flood
user_apps_dir: "{{ ansible_user_dir }}/.local/opt"

selinux_state: disabled

upgrade_commands:
  dnf:
    - systemctl restart chronyd
    - dnf -y upgrade --refresh
upgrade_schedule: weekly
upgrade_then_reboot: true
upgrade_service_name: upgrade-and-restart


pkgmgr_default_yes: true
pkgmgr_install_weak_deps: true
pkgmgr_dnf_deltarpm: true
pkgmgr_dnf_metadata_expire: 604800 # 1 week



users: []
users_admins: []
skel: []


hostname: null

timezone: Europe/Paris


http_domain: "{{ ansible_host }}"


caddy_https: true
caddy_email: null
caddy_entries: []
caddy_service: caddy
caddy_user: root
caddy_prometheus: false


cockpit_url_root: /cockpit
cockpit_allow_unencrypted: "{{ not caddy_https }}"
cockpit_login_to: true

user_mounts: []


containers: {}
containers_registries:
  - docker.io
quadlets: {}


compose_services: []
compose_dir: "{{ user_apps_dir }}"


repositories: []
repositories_dir: "{{ user_apps_dir }}"


user_services: {}
