server_tasks_base:
  # Core config
  - hostname
  - selinux
  - timezone
  - hosts

  # Packages
  - pkg-mgr-conf
  - packages
  - fuse
  # - periodic-upgrade
  - fzf

  # Users
  - cgroups
  - containers
  - users
  - paths

  # Services
  - firewall
  - caddy
  - cockpit
  - users_fstab
  # - promtail
  - tunnels
  - healthcheck

server_tasks: []

user_tasks_base:
  - dotfiles
  # - websites
  - containers
  - compose_services
  - repositories
  - mounts
  - services
  - minecraft

user_tasks: []

flood_url_root: /flood
user_apps_dir: "{{ ansible_user_dir }}/.local/opt"

selinux_state: disabled

packages_base:
  - bat
  - caddy
  - cockpit
  - cockpit-file-sharing
  - cockpit-navigator
  - cockpit-pcp
  - cockpit-podman
  - cockpit-storaged
  - dhcpdump
  - ffmpeg
  # - fzf
  - git
  - htop
  - httpie
  # - megatools
  - ncdu
  - neofetch
  - net-tools
  - nfs-utils
  - nmap
  - openssl-devel
  - podman
  - podman-compose
  # - promtail
  - screen
  - sqlite
  - sshfs
  - tree
  - util-linux-user
  - vim
  - wireguard-tools
  - zsh
  - zsh-syntax-highlighting
  # necessary to build Python (pyenv)
  - gcc
  - sqlite-devel
  - zlib-devel

packages: []

packages_remove:
  - crontabs # we prefer systemd-timers
  - haveged
  - udisks2-iscsi

# Override how to install packages for a given distro
packages_by_distro:
  Rocky:
    "9":
      # Not in EPEL repos for RHEL 9 (yet?)
      # - name: zsh-syntax-highlighting
      #   url: "http://rpmfind.net/linux/epel/8/Everything/{{ ansible_architecture }}/Packages/z/zsh-syntax-highlighting-0.7.1-1.el8.noarch.rpm"
      - name: fzf
        url: "https://www.rpmfind.net/linux/fedora/linux/updates/38/Everything/{{ ansible_architecture }}/Packages/f/fzf-0.42.0-1.fc38.{{ ansible_architecture }}.rpm"
      - name: caddy
        copr: "@caddy/caddy"
      - name: megatools
        url: https://www.rpmfind.net/linux/fedora/linux/releases/38/Everything/{{ ansible_architecture }}/os/Packages/m/megatools-1.11.1-1.fc38.{{ ansible_architecture }}.rpm
      - name: filebeat
        url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.11.3-{{ ansible_architecture }}.rpm
      # - name: centos-release-kmods
      #   url: https://cbs.centos.org/kojifiles/packages/centos-release-kmods/9/3.el9s/noarch/centos-release-kmods-9-3.el9s.noarch.rpm
      - name: promtail
        url: https://github.com/grafana/loki/releases/download/v2.8.11/promtail-2.8.11.{{ ansible_architecture }}.rpm
      - name: cockpit-identities
        url: https://github.com/45Drives/cockpit-identities/releases/download/v0.1.12/cockpit-identities-0.1.12-1.el8.noarch.rpm
      - name: cockpit-file-sharing
        url: https://github.com/45Drives/cockpit-file-sharing/releases/download/v4.2.5/cockpit-file-sharing-4.2.5-2.el8.noarch.rpm


upgrade_commands:
  dnf:
    - systemctl restart chronyd
    - dnf -y upgrade --refresh
upgrade_schedule: weekly
upgrade_then_reboot: true
upgrade_service_name: upgrade-and-restart


pkgmgr_default_yes: true
pkgmgr_install_weak_deps: true
pkgmgr_dnf_deltarpm: true
pkgmgr_dnf_metadata_expire: 604800 # 1 week



users: []
users_admins: []
skel: []


hostname: null

timezone: Europe/Paris


http_domain: "{{ ansible_host }}"


caddy_https: true
caddy_email: null
caddy_entries: []
caddy_service: caddy
caddy_user: root
caddy_prometheus: false


cockpit_url_root: /cockpit
cockpit_allow_unencrypted: "{{ not caddy_https }}"
cockpit_login_to: true

user_mounts: []


containers: {}
containers_registries:
  - docker.io
quadlets: {}


compose_services: []
compose_dir: "{{ user_apps_dir }}"


repositories: []
repositories_dir: "{{ user_apps_dir }}"


user_services: {}
