server_tasks_base:
  # Core config
  - hostname
  - selinux
  - timezone
  - hosts

  # Packages
  - pkg-mgr-conf
  - packages
  - fuse
  # - periodic-upgrade
  - fzf

  # Users
  - cgroups
  - containers
  - users
  - paths

  # Services
  - firewall
  - fail2ban
  - login_hook
  - caddy
  - cockpit
  - users_fstab
  # - promtail
  # - tunnels
  - healthcheck

server_tasks: []
server_tasks_disabled: []

user_tasks_base:
  - dotfiles
  # - websites
  - containers
  - compose_services
  - repositories
  - mounts
  - services
  - minecraft

user_tasks: []

flood_url_root: /flood
user_apps_dir: "{{ ansible_user_dir }}/.local/opt"

selinux_state: disabled

upgrade_commands:
  dnf:
    - systemctl restart chronyd
    - dnf -y upgrade --refresh
upgrade_schedule: weekly
upgrade_then_reboot: true
upgrade_service_name: upgrade-and-restart


pkgmgr_default_yes: true
pkgmgr_install_weak_deps: true
pkgmgr_dnf_deltarpm: true
pkgmgr_dnf_metadata_expire: 604800 # 1 week



users: []
users_admins:
  - tina
skel: []


hostname: null

timezone: Europe/Paris


http_domain: "{{ ansible_host }}"


caddy_https: true
caddy_email: null
caddy_entries: []
caddy_service: caddy
caddy_user: root
caddy_prometheus: false


cockpit_url_root: /cockpit
cockpit_allow_unencrypted: "{{ not caddy_https }}"
cockpit_login_to: true

user_mounts: []

user_shell: /bin/zsh


containers: {}
containers_registries:
  - docker.io
quadlets: {}


compose_services: []
compose_dir: "{{ user_apps_dir }}"


repositories: []
repositories_dir: "{{ user_apps_dir }}"


user_services: {}


backups_exclude_base:
  - "*.db-wal"
  - "*.db-shm"
  - "*.sqlite3-wal"
  - "*.sqlite3-shm"
  - "*/.backup*.db"
backups_exclude_extra: []
backups_exclude: "{{ backups_exclude_base + backups_exclude_extra }}"

backups_job_machine_paths_base:
  - "{{ ansible_user_dir }}/.ssh/"
  - "{{ ansible_user_dir }}/.history"

  - "{{ ansible_user_dir }}/.config/containers/containers.conf"
  - "{{ ansible_user_dir }}/.config/containers/hosts"
  - "{{ ansible_user_dir }}/.config/gh/"
  - "{{ ansible_user_dir }}/.config/pipus.txt"
  - "{{ ansible_user_dir }}/.config/rclone/"

  - /etc/healthcheck.yml
  - /etc/login-webhook.env
  - /etc/profile.d/motd.sh
  - /srv/www/errors/

  - /etc/cockpit/cockpit.conf
  - /etc/dnf/dnf.conf
  - /etc/fstab
  - /etc/group
  - /etc/gshadow
  - /etc/hosts
  - /etc/mdadm.conf
  - /etc/modules-load.d/
  - /etc/passwd
  - /etc/shadow
  - /etc/ssh/
  - /etc/subgid
  - /etc/subuid
  - /etc/udev/rules.d/
  - /etc/wireguard/
  - /etc/yum.repos.d/


backups_job_machine_paths_extra: []
backups_job_machine_paths: "{{ backups_job_machine_paths_base + backups_job_machine_paths_extra }}"

backups_repository: tina@asashio.tina.moe:Backups/Repositories/{{ ansible_hostname }}
backups_archive: '{now}'

backups_calendar: weekly

backups_jobs:
  machine:
    paths: "{{ backups_job_machine_paths }}"
    excludes: "{{ backups_exclude }}"
    repository: "{{ backups_repository }}"
    archive: "{{ backups_archive }}"
    calendar: "{{ backups_calendar }}"
