ports_by_value:
  2019: caddy_admin
  3000: flood
  3001: uptime_kuma
  3003: grafana
  3100: loki
  4533: navidrome
  7878: radarr
  8096: jellyfin
  8787: readarr
  8989: sonarr
  9080: promtail
  9090: cockpit
  9091: prometheus
  9100: prometheus_node_exporter
  9180: feishin
  9696: prowlarr
  10001: infra_webui
  10002: msnweb_demo
  10003: vaultwarden
  10004: msnweb
  10005: shlag_webui
  10006: nut
  10007: foil
  10008: aniboard
  10009: lapadmin
  10010: photongenic
  # 10011 taken
  10012: photongenic_share
  10013: qbittorrent_webui
  10014: kavita
  10015: komga
  10016: goty
  10017: grafana
  12345: alloy
  25565: minecraft

ports: "{{ ports_by_value | dict2items | items2dict(key_name='value', value_name='key') }}"
