backups_jobs: {}
# example
# my_job:
#  includes: ["/etc", "/home"]
#  excludes: ["*.db-shm", "*.db-wal"]
#  repository: user@backupserver:repo::{now}
#  calendar: weekly
#  random_delay: 10m
#  prepare_script: |
#    echo "Preparing backup..."
#  cleanup_script: |
#    echo "Cleaning up after backup..."

backup_repos_housekeeping_schedule: daily

backup_repos_keep_defaults:
  weekly: 8
  monthly: 12
  yearly: 5

backups_repos: []
# - path: "{{ ansible_facts.user_dir }}/Backups/Repositories/some_machine"
#   dry_run: true
#   keep:
#     weekly: 8
#     monthly: 12
#     yearly: 5

backups_secrets_file: /etc/backups-webhook.env
