driver:
  name: vagrant
platforms:
  - name: laffey
    box: rockylinux/9
    memory: 2G
    cpus: 2
  - name: turbo
    box: rockylinux/9
    memory: 1G
    cpus: 2
  - name: nagato
    box: rockylinux/9
    memory: 512M
    cpus: 1

provisioner:
  inventory:
    hosts:
      dev:
        hosts:
          laffey:
            http_domain: laffey.local
          turbo:
            http_domain: turbo.local
          nagato:
            http_domain: nagato.local
  env:
    ANSIBLE_CONFIG: ../../ansible.cfg
