---
driver:
  name: vagrant
platforms:
  - name: laffey
    box: generic/rocky9
  - name: turbo
    box: generic/rocky9

provisioner:
  inventory:
    hosts:
      dev:
        hosts:
          laffey:
          turbo:
  env:
    ANSIBLE_CONFIG: ../../ansible.cfg
