- name: Enable and start Cockpit
  service:
    name: cockpit.socket
    enabled: true
    state: started

- name: Configure Cockpit
  copy:
    dest: /etc/cockpit/cockpit.conf
    content: |
      [WebService]
      AllowUnencrypted = {{ cockpit_allow_unencrypted }}
      UrlRoot = {{ cockpit_url_root }}
      LoginTo = {{ cockpit_login_to }}
  notify: cockpit reload
