- name: Enable and start Cockpit
  service:
    name: cockpit.socket
    enabled: true
    state: started

- name: Configure Cockpit
  copy:
    dest: /etc/cockpit/cockpit.conf
    content: |
      [WebService]
      Origins = {% if caddy_https %}https{% else %}http{% endif %}://{{ cockpit_origin | default(http_domain) }}
      AllowUnencrypted = {{ cockpit_allow_unencrypted }}
      UrlRoot = {{ cockpit_url_root }}
      LoginTo = {{ cockpit_login_to }}
      ForwardedForHeader = X-Forwarded-For
  notify: cockpit reload

- name: Disable Cockpit motd
  file:
    src: /dev/null
    dest: /etc/motd.d/cockpit
    state: link
    force: true
