- name: Update /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^{{ item.key }} {{ item.value }}$'
    line: '{{ item.key }} {{ item.value }}'
  loop: '{{ hosts_map | default({}) | dict2items }}'
  notify: dnsmasq restart
