- name: Create service file
  include_role:
    name: common
    tasks_from: create_service
  vars:
    service_name: periodic-upgrade
    service_schedule: "*-*-1,7,14,21,28 04:30:00"
    service_script: |
      {{ periodic_upgrade_commands[ansible_pkg_mgr] | join(";") }}
      {% if periodic_upgrade_then_reboot %}
      sleep 1m; shutdown -r +15
      {% endif %}
