- hosts: all
  become: true
  become_user: "{{ deploy_user }}"
  vars:
    deploy_dir: "{{ user_apps_dir }}/MechaDon2"
    deploy_git: https://github.com/asso-msn/MechaDon2.git
  tasks:
    - assert:
        that: deploy_version is defined
    - name: Check if MechaDon directory exists
      stat:
        path: "{{ deploy_dir }}"
      register: _deploy_dir_stat
    - name: Fail if MechaDon directory does not exist
      fail:
        msg: "MechaDon directory does not exist"
      when:
        - not _deploy_dir_stat.stat.exists
        - not _deploy_dir_stat.stat.isdir
    - name: Fetch version {{ deploy_version }} of MechaDon
      git:
        repo: "{{ deploy_git }}"
        dest: "{{ deploy_dir }}"
        version: "{{ deploy_version }}"
      register: _deploy_git_action
      changed_when: _deploy_git_action.after != _deploy_git_action.before
      notify: restart

  handlers:
    - name: Restart MechaDon
      systemd:
        name: mechadon
        state: restarted
        scope: user
      listen: restart
