backups_job_machine_paths_extra:
  - "{{ ansible_user_dir }}/.local/share/wg-easy/"

packages_base:
  - borgbackup
  - caddy
  - htop
  - fail2ban
  - ncdu
  - neofetch
  - net-tools
  - podman
  - rclone
  - screen
  - sshfs
  - tree
  - vim
  - zsh
  - zsh-syntax-highlighting

server_tasks_disabled:
  - cockpit

quadlets:
  wg_easy:
    image: ghcr.io/wg-easy/wg-easy
    tag: latest
    volumes:
      - "{{ ansible_user_dir }}/.local/share/wg-easy:/etc/wireguard"
    ports:
      - "51820:51820/udp"
      - "{{ loopback_ip }}:51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1
    env:
      WG_HOST: "{{ ansible_host }}"
      WG_DEVICE: tap0
