users_admins:
  - tina

repositories:
  - src: https://github.com/asso-msn/msn-web
    name: msnweb-demo
    version: develop
  - src: https://github.com/asso-msn/msn-web
    name: msnweb
    version: release
  - src: git@github.com:Tina-otoge/couscous-infra.git
    name: couscous
    version: master


user_services:
  couscous:
    workdir: "{{ repositories_dir }}/couscous"
    cmd: "{{ compose_setup }}"
  msnweb_demo:
    workdir: "{{ repositories_dir }}/msnweb-demo"
    cmd: |
      {{ python_setup }}
      alembic upgrade head
      flask setup
      RUN_TASKS=1 flask run -h {{ loopback_ip }} -p {{ msnweb_demo_port }}
  msnweb:
    workdir: "{{ repositories_dir }}/msnweb"
    cmd: |
      {{ python_setup }}
      alembic upgrade head
      flask setup
      RUN_TASKS=1 flask run -h {{ loopback_ip }} -p {{ msnweb_port }}
  rclone_msn:
    workdir: "{{ ansible_user_dir }}/wwws/asso-msn.fr/assets"
    script: |
      while true; do
        date
        rclone sync -v msn:Website/Assets/ .
        echo Waiting 60s
        sleep 60
      done

caddy_entries:
  - domain: couscous.tina.moe
    robots: false
    file: tina
    reverses:
      - to: 57348

  # MSN
  - domain: demo.asso-msn.fr
    robots: false
    file: msn
    reverses:
      - to: "{{ msnweb_demo_port }}"
  - domain: asso-msn.fr
    file: msn
    reverses:
      - to: "{{ msnweb_port }}"
    extra: |
      handle_path /assets/* {
        root * /home/tina/wwws/asso-msn.fr/assets
        file_server
      }

      handle_path /discord {
        redir https://discord.gg/k4CVGDQ
      }
