http_domain: laffey.tina.moe
public_ip: 198.27.82.171
graylog_url: https://graylog.tina.moe/

user_tasks:
  - prometheus
  - loki

packages:
  - libcurl-devel # for NUT
  - syncthing
  - ufw

firewall:
  default: allow
  rules:
    - port: "{{ prometheus_node_exporter_port }}"
      action: deny
    - port: "{{ prometheus_node_exporter_port }}"
      from: "{{ public_ip }}"
      action: allow

    - port: "{{ prometheus_port }}"
      action: deny
    - port: "{{ prometheus_port }}"
      from: "{{ public_ip }}"
      action: allow

    - port: "{{ caddy_admin_port }}"
      action: deny
    - port: "{{ caddy_admin_port }}"
      from: "{{ public_ip }}"
      action: allow

    - port: "{{ loki_port }}"
      action: deny
    - port: "{{ loki_port }}"
      from: "{{ public_ip }}"
      action: allow

users:
  - akeyro
  - koneko
  - noa
  - platea
  - reaxt
  - sayaka
  - test

users_admins:
  - tina

skel:
  - www
  - wwws/example.com

caddy_prometheus: true
caddy_global_extra: |
  admin :{{ caddy_admin_port }}

# caddy_logs_outputs:
#   graylog: net localhost:5555

caddy_extra: |
  import users.d/*.conf

caddy_error_handlers:
  - 502

caddy_entries:
  # Machine domain
  - domain: "{{ http_domain }}"
    root: /home/tina/wwws/laffey
    file: tina
    reverses:
      - path: /fail
        to: 0
      - path: "{{ cockpit_url_root }}"
        to: 9090
      - path: "{{ flood_url_root }}"
        to: 3000
      - path: /qbit
        remove_path: true
        to: "{{ qbittorrent_webui_port }}"
      - path: /syncthing
        to: 8384
        extra: header_up Host {upstream_hostport}
        remove_path: true
    extra: |
      @userdir {
        path_regexp userdir ^/~(\w+)/
      }
      handle @userdir {
        uri strip_prefix /~{re.userdir.1}/
        file_server browse {
          root /home/{re.userdir.1}/www/
        }
      }

      @drs_videos {
        path_regexp drs_videos ^/~tina/lap/drs_videos/(.*)\.mp4
      }
      redir @drs_videos https://drs.lelap.in/videos/{re.drs_videos.1}.mp4

  # Tina
  - domain: grafana.tina.moe
    robots: false
    file: tina
    reverses:
      - to: "{{ grafana_port }}"
  - domain: pixiv.tina.moe
    file: tina
    robots: false
    reverses:
      - to: 8282
    # extra: |
    #   @artworks path_regexp ^/\w{2}/artworks/(\d+)
    #   handle @artworks {
    #     redir /artworks/{re.artworks.1}
    #   }
  - domain: www.pixiv.tina.moe
    file: tina
    extra: |
      redir https://pixiv.tina.moe{uri}
  - domain: taiko.tina.moe
    robots: false
    file: tina
    reverses:
      - to: 5000
  - domain: drs.tina.moe
    robots: false
    file: tina
    extra: |
      redir https://drs.lelap.in{uri}
  - domain: nut.tina.moe
    robots: false
    file: tina
    reverses:
      - to: "{{ nut_port }}"

paths:
  /srv/media:
    owner: tina

user_services:
  infra_webui:
    workdir: "{{ repositories_dir }}/infra-webui"
    cmd: |
      {{ python_setup }}
      pip install gunicorn
      gunicorn src:app -b {{ loopback_ip }}:{{ infra_webui_port }}
  couscous_infra:
    workdir: "{{ repositories_dir }}/couscous"
    cmd: "{{ compose_setup }}"
  six:
    workdir: "{{ compose_dir }}/six"
    cmd: "{{ compose_setup }}"
    depend: home-tina-mnt-turbo.mount
  # flood:
  #   workdir: "{{ compose_dir }}/flood"
  #   cmd: |
  #     rm -rfv {{ ansible_user_dir }}/.config/flood/rtorrent/rtorrent.sock
  #     {{ compose_setup }}
  pixivfe:
    enabled: false
    workdir: "{{ repositories_dir }}/PixivFE"
    cmd: |
      ./patch/patch.sh
      {{ compose_setup }}
  # taiko:
  #   workdir: "{{ repositories_dir }}/TaikoLocalServer"
  #   cmd: |
  #     chmod +x TaikoLocalServer
  #     ./TaikoLocalServer
  taiko:
    workdir: "{{ repositories_dir }}/tls-jp-april-2023"
    cmd: |
      dotnet run --project TaikoLocalServer
  syncthing:
    create: false
  rclone_msn:
    workdir: "{{ ansible_user_dir }}/wwws/asso-msn.fr/assets"
    script: |
      while true; do
        date
        rclone sync -v msn:Website/Assets/ .
        echo Waiting 60s
        sleep 60
      done
  rclone_tina:
    workdir: "{{ ansible_user_dir }}/wwws/tina/assets/"
    script: |
      while true; do
        date
        rclone sync -v tina:/ cloud
        echo Waiting 60s
        sleep 60
      done
  watchdog_six:
    script: |
      restart_service() {
        echo "Test file not found, restarting"
        systemctl --user restart six
      }

      while true; do
        podman exec six_jellyfin_1 bash -c '[ -d /mnt/sakura/public/Works/Music/Singles/ ]' || restart_service
        sleep 60
      done
  nut:
    workdir: "{{ repositories_dir }}/nut"
    enabled: false
    cmd: |
      {{ python_setup }}
      python nut.py -s -S -m {{ loopback_ip }} -p {{ nut_port }}
  ownfoil:
    enabled: false
    workdir: "{{ repositories_dir }}/ownfoil"
    # Chunked send implementation not supported by gunicorn so we use Flask dev
    # server
    cmd: |
      {{ python_setup }}
      FLASK_APP=app/app:app flask run -h {{ loopback_ip }} -p {{ foil_port }}

quadlets:
  # prometheus:
  #   image: prom/prometheus
  #   tag: latest
  #   user: "{{ ansible_user_id }}"
  #   network: host
  #   exec: |
  #     --config.file=/etc/prometheus/prometheus.yml
  #     --storage.tsdb.path=/prometheus
  #     --web.listen-address="{{ loopback_ip }}:{{ prometheus_port }}"
  #   volumes:
  #     - "{{ ansible_user_dir }}/.config/prometheus:/etc/prometheus"
  #     - "{{ ansible_user_dir }}/.local/share/prometheus:/prometheus"
  # grafana:
  #   image: grafana/grafana-oss
  #   tag: main
  #   network: host
  #   env:
  #     GF_SERVER_HTTP_ADDR: "{{ loopback_ip }}"
  #     GF_SERVER_HTTP_PORT: "{{ grafana_port }}"
  #   user: root
  #   volumes:
  #     - "{{ ansible_user_dir }}/.local/share/grafana:/var/lib/grafana"
  # loki:
  #   image: grafana/loki
  #   tag: main
  #   user: root
  #   ports:
  #     - "{{ loki_port }}:3100"
  #   volumes:
  #     - "{{ ansible_user_dir }}/.config/loki:/etc/loki"
  #     - "{{ ansible_user_dir }}/.local/share/loki:/loki"
  qbit:
    image: lscr.io/linuxserver/qbittorrent
    tag: latest
    ports:
      - "{{ loopback_ip }}:{{ qbittorrent_webui_port }}:{{ qbittorrent_webui_port }}"
    volumes:
      - "{{ ansible_user_dir }}/.config/qbittorrent:/config"
      - "{{ ansible_user_dir }}/mnt/sakura-private/Downloads/torrents:/mnt/downloads"
      - "{{ ansible_user_dir }}/mnt/sakura:/mnt/sakura/public"
    env: "{{ linuxserver_env }}"
  teamspeak:
    image: teamspeak
    tag: latest
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    env:
      TS3SERVER_LICENSE: accept
    volumes:
      - "{{ ansible_user_dir }}/.config/teamspeak:/var/ts3server"

compose_services:
  # - six
  - flood

user_mounts:
  - what: tina@turbo.tina.moe:/
    where: "{{ ansible_user_dir }}/mnt/turbo"
    type: fuse.sshfs
    description: Savatier Home Freebox VM
    test: "{{ ansible_user_dir }}/mnt/turbo/mnt/Freebox/Enregistrements"
  - what: tina@nagato.tina.moe:/
    where: "{{ ansible_user_dir }}/mnt/nagato"
    type: fuse.sshfs
    description: Nagato
    test: "{{ ansible_user_dir }}/mnt/nagato/home/tina/"

torrents_dir: "{{ ansible_user_dir }}/mnt/sakura-private/Downloads/torrents"
