http_domain: laffey.tina.moe

tasks_list:
  - filebeat

packages:
  - filebeat

skeleton_dirs:
  - www
  - wwws/example.com

users:
  - akeyro
  - koneko
  - noa
  - platea
  - reaxt
  - sayaka
  - test

users_admins:
  - tina

switch_ip: 198.27.82.171

caddy_service: caddy-root

caddy_logs_outputs:
  graylog: net localhost:5555

caddy_extra: |
  import users.d/*.conf

caddy_entries:
  - domain: "{{ http_domain }}"
    root: /home/tina/wwws/laffey
    file: tina
    reverses:
      - path: "{{ cockpit_url_root }}"
        to: 9090
      - path: "{{ flood_url_root }}"
        to: 3000
      - path: /qbit
        remove_path: true
        to: "{{ qbittorrent_webui_port }}"
      - path: "{{ semaphore_url_root }}"
        to: 3005
    extra: |
      @userdir {
        path_regexp userdir ^/~(\w+)/
      }
      handle @userdir {
        uri strip_prefix /~{re.userdir.1}/
        file_server browse {
          root /home/{re.userdir.1}/www/
        }
      }
  - domain: kuma.{{ http_domain }}
    file: tina
    reverses:
      - to: "{{ uptime_kuma_port }}"
  - domain: kasm.{{ http_domain }}
    file: tina
    extra: |
      reverse_proxy localhost:8443 {
        transport http {
          tls
          tls_insecure_skip_verify
        }
      }
  - domain: graylog.tina.moe
    file: tina
    reverses:
      - to: "{{ graylog_port }}"
  - domain: tina.moe
    root: /home/tina/wwws/tina
    file: tina
    reverses:
      - path: /infra
        to: "{{ infra_webui_port }}"
        remove_path: true
    extra: |
      handle_path /private/* {
        root * /home/tina/wwws/private
        file_server
      }
      redir /private /private/
  - domain: couscous.tina.moe wiki.couscous.tina.moe
    robots: false
    file: tina
    reverses:
      - to: 57348
  - domain: six.savatier.fr
    root: /home/tina/wwws/six
    file: tina_six
    extra: |
      redir https://six.tina.moe{uri}
  - domain: six.tina.moe
    root: /home/tina/wwws/six
    file: tina_six
    reverses:
      - path: /jellyfin
        to: "{{ jellyfin_port }}"

paths:
  /srv/media:
    owner: tina

repositories:
  - src: https://github.com/Tina-otoge/infra-webui

user_services:
  infra_webui:
    workdir: "{{ repositories_dir }}/infra-webui"
    cmd: |
      {{ python_setup }}
      pip install gunicorn
      gunicorn src:app -b {{ loopback_ip }}:{{ infra_webui_port }}
  couscous_infra:
    workdir: "{{ repositories_dir }}/couscous"
    cmd: "{{ compose_setup }}"
  graylog:
    workdir: "{{ compose_dir }}/graylog"
    cmd: "{{ compose_setup }}"
  six:
    workdir: "{{ compose_dir }}/six"
    cmd: "{{ compose_setup }}"
    depend: home-tina-mnt-turbo.service
  flood:
    workdir: "{{ compose_dir }}/flood"
    cmd: |
      rm -rfv {{ ansible_user_dir }}/.config/flood/rtorrent/rtorrent.sock
      {{ compose_setup }}
  semaphore:
    workdir: "{{ compose_dir }}/semaphore"
    cmd: "{{ compose_setup }}"

quadlets:
  prometheus:
    image: prom/prometheus
    tag: latest
    user: "{{ ansible_user_id }}"
    ports:
      - "{{ loopback_ip }}:{{ prometheus_port }}:9090"
    volumes:
      - "{{ ansible_user_dir }}/.config/prometheus:/etc/prometheus"
      - "{{ ansible_user_dir }}/.local/share/prometheus:/prometheus"

containers:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    tag: latest
    ports:
      - "{{ loopback_ip }}:{{ qbittorrent_webui_port }}:{{ qbittorrent_webui_port }}"
    volumes:
      - "{{ ansible_user_dir }}/.config/qbittorrent:/config"
      - "{{ ansible_user_dir }}/mnt/sakura-private/Downloads/torrents:/mnt/downloads"
    env: "{{ linuxserver_env }}"
  uptime_kuma:
    image: louislam/uptime-kuma
    tag: latest
    ports:
      - "{{ loopback_ip }}:{{ uptime_kuma_port }}:{{ uptime_kuma_port }}"
    volumes:
      - uptime-kuma:/app/data

graylog_url: https://graylog.tina.moe/

compose_services:
  - graylog
  - six
  - flood
  - semaphore

user_mounts:
  - what: tina@turbo.tina.moe:/
    where: "{{ ansible_user_dir }}/mnt/turbo"
    type: fuse.sshfs
    description: Savatier Home Freebox VM
    test: "{{ ansible_user_dir }}/mnt/turbo/mnt/Freebox"

torrents_dir: "{{ ansible_user_dir }}/mnt/sakura-private/Downloads/torrents"

semaphore_url_root: /semui
semaphore_url: https://{{ http_domain }}{{ semaphore_url_root }}
