http_domain: laffey.tina.moe

tasks_list:
  - filebeat

packages:
  - filebeat

skeleton_dirs:
  - www
  - wwws/example.com

users:
  - akeyro
  - koneko
  - noa
  - platea
  - reaxt
  - sayaka
  - test

users_admins:
  - tina

switch_ip: 198.27.82.171

caddy_service: caddy-root

caddy_logs_outputs:
  graylog: net localhost:5555

caddy_extra: |
  import users.d/*.conf

caddy_entries:
  - domain: "{{ http_domain }}"
    root: /home/tina/wwws/laffey
    file: tina
    reverses:
      - path: "{{ cockpit_url_root }}"
        to: 9090
      - path: /flood
        to: 3000
        extra: |
          header_up X-Graylog-Server-URL {{ graylog_url }}
    extra: |
      @userdir {
        path_regexp userdir ^/~(\w+)/
      }
      handle @userdir {
        uri strip_prefix /~{re.userdir.1}/
        file_server browse {
          root /home/{re.userdir.1}/www/
        }
      }
  - domain: graylog.tina.moe
    file: tina
    reverses:
      - to: "{{ graylog_port }}"
  - domain: tina.moe
    root: /home/tina/wwws/tina
    file: tina
    reverses:
      - path: /infra
        to: "{{ infra_webui_port }}"
        remove_path: true
    extra: |
      handle_path /private/* {
        root * /home/tina/wwws/private
        file_server
      }
      redir /private /private/
  # - domain: "{{ keycloak_url }}"
  #   file: tina
  #   reverses:
  #     - to: "{{ keycloak_port }}"
  # - domain: "{{ outline_url }}"
  #   file: tina
  #   reverses:
  #     - to: "{{ outline_port }}"
  - domain: couscous.tina.moe
    robots: false
    file: tina
    reverses:
      - to: 57348
  - domain: six.savatier.fr
    root: /home/tina/wwws/six
    file: tina_six
    reverses:
      # - path: /ping
      #   to: "{{ uptimekuma_port }}"
      # - path: /prowlarr
      #   to: "{{ prowlarr_port }}"
      # - path: /sonarr
      #   to: "{{ sonarr_port }}"
      # - path: /radarr
      #   to: "{{ radarr_port }}"
      # - path: /lidarr
      #   to: "{{ lidarr_port }}"
      # - path: /readarr
      #   to: "{{ readarr_port }}"
      - path: /jellyfin
        to: "{{ jellyfin_port }}"
      # - path: /torrents
      #   remove_path: true
      #   to: "{{ qbittorrent_webui_port }}"
  # - domain: seerr.savatier.fr
  #   file: tina_six
  #   reverses:
  #     - to: "{{ jellyseerr_port }}"

paths:
  /srv/media:
    owner: tina

repositories:
  - src: https://github.com/Tina-otoge/infra-webui

user_services:
  infra_webui:
    workdir: "{{ repositories_dir }}/infra-webui"
    cmd: |
      {{ python_setup }}
      pip install gunicorn
      gunicorn src:app -b {{ loopback_ip }}:{{ infra_webui_port }}
  couscous_infra:
    workdir: "{{ repositories_dir }}/couscous"
    cmd: "{{ compose_setup }}"
  graylog:
    workdir: "{{ compose_dir }}/graylog"
    cmd: "{{ compose_setup }}"
  six:
    workdir: "{{ compose_dir }}/six"
    cmd: "{{ compose_setup }}"

containers: {}
  # affine:
  #   image: ghcr.io/toeverything/affine-self-hosted
  #   tag: latest
  #   ports:
  #     - "{{ loopback_ip }}:{{ affine_port }}:3000"
  #   volumes:
  #     - "{{ ansible_user_dir }}/.local/share/affine:/app/data"
_no:
  keycloak:
    image: quay.io/keycloak/keycloak
    tag: 22.0.5
    ports:
      - "{{ loopback_ip }}:{{ keycloak_port }}:8080"
    user: root
    env:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY: "edge"
    volumes:
      - "keycloak:/opt/keycloak/data"
    command: start-dev
  # Savatier Studio 6
  six-jellyfin:
    image: lscr.io/linuxserver/jellyfin
    ports:
      - "{{ loopback_ip }}:{{ jellyfin_port }}:{{ jellyfin_port }}"
    volumes:
      - "{{ ansible_user_dir }}/mnt/freebox:/mnt/Freebox"
      - "{{ ansible_user_dir }}/.config/jellyfin:/config"
      - "{{ ansible_user_dir }}/.cache/jellyfin:/cache"
    env: "{{ linuxserver_env }}"
    network: six
    # pod: six
  six-jellyseerr:
    image: fallenbagel/jellyseerr
    tag: latest
    ports:
      - "{{ loopback_ip }}:{{ jellyseerr_port }}:{{ jellyseerr_port }}"
    volumes:
      - "{{ ansible_user_dir }}/.config/jellyseerr:/app/config"
    network: six
    # pod: six
  six-sonarr:
    image: lscr.io/linuxserver/sonarr
    tag: latest
    ports:
      - "{{ loopback_ip }}:{{ sonarr_port }}:{{ sonarr_port }}"
    volumes:
      - "{{ ansible_user_dir }}/.config/sonarr:/config"
      - "{{ ansible_user_dir }}/mnt/freebox:/mnt/Freebox"
    env: "{{ linuxserver_env }}"
    network: six
    # pod: six
  six-radarr:
    image: lscr.io/linuxserver/radarr
    tag: latest
    ports:
      - "{{ loopback_ip }}:{{ radarr_port }}:{{ radarr_port }}"
    volumes:
      - "{{ ansible_user_dir }}/.config/radarr:/config"
      - "{{ ansible_user_dir }}/mnt/freebox:/mnt/Freebox"
    env: "{{ linuxserver_env }}"
    network: six
    # pod: six
  six-prowlarr:
    image: lscr.io/linuxserver/prowlarr
    tag: latest
    ports:
      - "{{ loopback_ip }}:{{ prowlarr_port }}:{{ prowlarr_port }}"
    volumes:
      - "{{ ansible_user_dir }}/.config/prowlarr:/config"
      - "{{ ansible_user_dir }}/mnt/freebox:/mnt/Freebox"
    env: "{{ linuxserver_env }}"
    network: six
    # pod: six
  six-flaresolverr:
    image: flaresolverr/flaresolverr
    tag: latest
    ports:
      - "{{ switch_ip }}:{{ flaresolverr_port }}:{{ flaresolverr_port }}"
    network: six
    # pod: six
  six-qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    tag: latest
    ports:
      - "{{ loopback_ip }}:{{ qbittorrent_webui_port }}:{{ qbittorrent_webui_port }}"
    volumes:
      - "{{ ansible_user_dir }}/.config/qbittorrent:/config"
      - "{{ ansible_user_dir }}/mnt/freebox:/mnt/Freebox"
    env: "{{ linuxserver_env }}"
    network: six
    # pod: six

  # mc:
  #   image: eclipse-temurin:17
  #   ports:
  #     - 25565
  #   volumes:

outline_url: https://notes.tina.moe
bookstack_url: https://books.tina.moe
affine_url: https://notes.tina.moe
keycloak_url: https://auth.tina.moe
graylog_url: https://graylog.tina.moe/

compose_services:
  # - bookstack
  # - outline
  # - authentik
  - graylog
  - six

user_mounts:
  - what: tina@turbo.tina.moe:/
    where: "{{ ansible_user_dir }}/mnt/turbo"
    type: fuse.sshfs
    description: Savatier Home Freebox VM
    test: "{{ ansible_user_dir }}/mnt/turbo/mnt/Freebox"
