skeleton_dirs:
  - www
  - wwws/example.com

users:
  - akeyro
  - koneko
  - noa
  - platea
  - reaxt
  - sayaka
  - test

users_admins:
  - tina

caddy_entries:
  - domain: "{{ http_domain }}"
    root: /home/tina/wwws/laffey
    file: tina
    reverses:
      - path: "{{ cockpit_url_root }}"
        to: 9090
      - path: /flood
        to: 3000
    extra: |
      @userdir {
        path_regexp userdir ^/~(\w+)/
      }
      handle @userdir {
        root * /home/{re.userdir.1}/www
        file_server browse
      }

paths:
  /srv/media:
    owner: tina

containers:
  jellyfin:
    image: jellyfin/jellyfin
    ports:
      - 8096
    volumes:
      - /srv/media:/media
    user: tina
    labels:
      - io.containers.autoupdate=registry
  mc:
    image: eclipse-temurin:17
    ports:
      - 25565
    volumes:
