tasks_list:
  - samba

packages:
  - cifs-utils
  - samba
  - samba-client
  - samba-common
  - syncthing
  - wsdd


users_admins:
  - tina

upgrade_then_reboot: false

user_mounts:
  - what: tina@turbo.tina.moe:/
    where: "{{ ansible_user_dir }}/mnt/turbo"
    type: fuse.sshfs
    description: Savatier Home Freebox VM
    test: "{{ ansible_user_dir }}/mnt/turbo/mnt/Freebox"
    options: "idmap=user,follow_symlinks,allow_other"

caddy_entries:
  - domain: "{{ http_domain }}"
    root: /srv/www/nagato
    browser: true
    file: nagato
    reverses:
      - path: "{{ cockpit_url_root }}"
        to: "{{ cockpit_port }}"
      - path: /syncthing
        to: 8384
        extra:
          header_up Host {upstream_hostport}
        remove_path: true
    extra: |
      handle_path /files/* {
        root * /srv/www/files
        file_server browse
      }
  - domain: arcade.tina.moe
    file: arcade
    extra: |
      handle {
        reverse_proxy /photon/* :7001
        redir /photon /photon/

        redir / /photon
      }
  - domain: turbo.tina.moe
    file: nagato
    extra: |
      handle {
        redir https://nagato.tina.moe{uri}
      }

repositories:
  - src: https://github.com/Tina-otoge/photongenic

user_services:
  photon:
    workdir: "{{ repositories_dir }}/photongenic"
    cmd: |
      {{ python_setup }}
      pip install gunicorn
      (python archive.py &)
      SCRIPT_NAME=/photon gunicorn -w 4 webui.app:app -b 127.0.0.1:7001
  syncthing:
    create: false
