tasks_list:
  - samba

packages:
  - cifs-utils
  - samba
  - samba-client
  - samba-common
  - syncthing
  - wsdd


users_admins:
  - tina

caddy_https: false

caddy_entries:
  - domain: "{{ http_domain }}"
    root: /srv/www/nagato
    browser: true
    file: nagato
    reverses:
      - path: "{{ cockpit_url_root }}"
        to: "{{ cockpit_port }}"
      - path: /syncthing
        to: 8384
        extra:
          header_up Host {upstream_hostport}
        remove_path: true

user_services:
  syncthing:
    create: false
