tasks_list:
  - samba

packages:
  - cifs-utils
  - samba
  - samba-client
  - samba-common
  - syncthing
  - wsdd


users_admins:
  - tina

upgrade_then_reboot: false

caddy_https: false

caddy_entries:
  - domain: "{{ http_domain }}"
    root: /srv/www/nagato
    browser: true
    file: nagato
    reverses:
      - path: "{{ cockpit_url_root }}"
        to: "{{ cockpit_port }}"
      - path: /syncthing
        to: 8384
        extra:
          header_up Host {upstream_hostport}
        remove_path: true
  - domain: arcade.tina.moe
    file: arcade
    extra: |
      handle {
        reverse_proxy /photon/* :7001
        redir /photon /photon/

        redir / /photon
      }

repositories:
  - src: https://github.com/Tina-otoge/photongenic

user_services:
  photon:
    workdir: "{{ repositories_dir }}/photongenic"
    cmd: |
      {{ python_setup }}
      pip install gunicorn
      (python archive.py &)
      SCRIPT_NAME=/photon gunicorn -w 4 webui.app:app -b 127.0.0.1:7001
  syncthing:
    create: false
