tasks_list:
  - samba

packages:
  - cifs-utils
  - samba
  - samba-client
  - samba-common
  - syncthing
  - wsdd


users_admins:
  - tina

upgrade_then_reboot: false

user_mounts:
  - what: tina@turbo.tina.moe:/
    where: "{{ ansible_user_dir }}/mnt/turbo"
    type: fuse.sshfs
    description: Savatier Home Freebox VM
    test: "{{ ansible_user_dir }}/mnt/turbo/mnt/Freebox"
    options: "idmap=user,follow_symlinks,allow_other"

caddy_error_handlers:
  - 502

caddy_entries:
  - domain: "{{ http_domain }}"
    root: /srv/www/nagato
    browser: true
    file: nagato
    robots: false
    reverses:
      - path: /fail
        to: 0
      - path: "{{ cockpit_url_root }}"
        to: "{{ cockpit_port }}"
      - path: /syncthing
        to: 8384
        extra:
          header_up Host {upstream_hostport}
        remove_path: true
    extra: |
      handle_path /files/* {
        root * /srv/www/files
        file_server browse
      }
  - domain: arcade.tina.moe
    file: tina
    robots: false
    extra: |
      @private remote_ip private_ranges
      @public not remote_ip private_ranges

      handle @public {
        handle / {
                root * /srv/www/arcade/public
                file_server
        }
        handle /* {
                redir * /
        }
      }

      handle @private {
        handle / {
                root * /srv/www/arcade/private
                file_server
        }
        reverse_proxy /photon/* :7001
        redir /photon /photon/

        redir / /photon
      }
  - domain: turbo.tina.moe
    file: tina
    robots: false
    extra: |
      handle {
        redir https://nagato.tina.moe{uri}
      }
  - domain: ani.turbo.tina.moe
    file: tina
    robots: false
    extra: |
      redir https://aniboard.tina.moe{uri}
  - domain: foil.tina.moe
    file: tina
    robots: false
    reverses:
      - to: "{{ foil_port }}"
  - domain: aniboard.tina.moe
    file: tina
    robots: false
    reverses:
      - to: "{{ aniboard_port }}"

repositories:
  - src: https://github.com/Tina-otoge/photongenic

user_services:
  photon:
    workdir: "{{ repositories_dir }}/photongenic"
    cmd: |
      {{ python_setup }}
      pip install gunicorn
      (python archive.py &)
      SCRIPT_NAME=/photon gunicorn -w 4 webui.app:app -b 127.0.0.1:7001
  syncthing:
    create: false
  aniboard:
    workdir: "{{ repositories_dir }}/AniBoard"
    cmd: |
      {{ python_setup }}
      gunicorn -w 4 app:app -b {{ loopback_ip }}:{{ aniboard_port }}


quadlets:
  ownfoil:
    image: a1ex4/ownfoil
    ports:
      - "{{ loopback_ip }}:{{ foil_port }}:8465"
    volumes:
      - "{{ ansible_user_dir }}/.config/ownfoil:/config"
      - "{{ ansible_user_dir }}/Games/Console/Switch:/games"
