tasks_list:
  - samba

users_admins:
  - tina

caddy_https: false

caddy_entries:
  - domain: "{{ http_domain }}"
    root: /srv/www/nagato
    browser: true
    file: nagato
    reverses:
      - path: "{{ cockpit_url_root }}"
        to: "{{ cockpit_port }}"

packages:
  - cifs-utils
  - cockpit-file-sharing
  - samba
  - samba-common
  - samba-client
  - wsdd
