hostname: TurboVM

packages:
  - dnsmasq
  - syncthing

server_tasks:
  - dnsmasq

users_admins:
  - tina

http_domain: turbo.tina.moe

hosts_map:
  192.168.0.2: turbovm.lan turbo.lan turbo.tina.moe
  192.168.0.6: nagato.lan arcade.tina.moe nagato.tina.moe
  192.168.0.10: deck.lan
  192.168.0.13: jubeat.lan
  192.168.0.14: ninox.lan
  192.168.0.16: dragoon.lan
  192.168.0.18: tricoro.lan
  192.168.0.20: rootage.lan
  192.168.0.23: copula.lan
  192.168.0.52: tinarcade.lan
  192.168.0.69: blandine.lan

  192.168.27.70: nagato.vpn.lan
  192.168.27.71: turbo.vpn.lan
  192.168.27.73: ninox.vpn.lan

  127.0.0.2: sddt.amlog.sys-all.net


caddy_entries:
  - domain: "{{ http_domain }}"
    robots: false
    root: /home/tina/wwws/turbo
    browser: true
    file: turbo
    reverses:
      - path: "{{ cockpit_url_root }}"
        to: "{{ cockpit_port }}"
      - path: /flood
        to: "{{ flood_port }}"
      - path: /syncthing
        to: 35315
        extra:
          header_up Host {upstream_hostport}
        remove_path: true


user_services:
  syncthing:
    create: false
