hostname: TurboVM

packages:
  - dnsmasq

tasks_list:
  - dnsmasq

users_admins:
  - tina

http_domain: turbo.tina.moe

hosts_map:
  192.168.0.2: turbovm.lan turbo.lan turbo.tina.moe arcade.tina.moe
  192.168.0.6: nagato.lan
  192.168.0.10: deck.lan
  192.168.0.13: jubeat.lan
  192.168.0.14: ninox.lan
  192.168.0.16: dragoon.lan
  192.168.0.18: tricoro.lan
  192.168.0.20: rootage.lan
  192.168.0.23: copula.lan
  192.168.0.69: blandine.lan

  192.168.27.70: nagato.vpn.lan
  192.168.27.71: turbo.vpn.lan
  192.168.27.73: ninox.vpn.lan

  127.0.0.2: sddt.amlog.sys-log.net


caddy_entries:
  - domain: "{{ http_domain }}"
    root: /home/tina/wwws/turbo
    browser: true
    file: turbo
    reverses:
      - path: "{{ cockpit_url_root }}"
        to: "{{ cockpit_port }}"
      - path: /flood
        to: "{{ flood_port }}"
  - domain: "ani.{{ http_domain }}"
    file: turbo
    reverses:
      - to: 57401
  - domain: "arcade.tina.moe"
    file: arcade
    extra: |
        @private remote_ip private_ranges
        @public not remote_ip private_ranges

        handle @public {
                handle / {
                        root * /home/tina/wwws/arcade/public
                        file_server
                }
                handle /* {
                        redir * /
                }
        }

        handle @private {
                reverse_proxy /photon/* :7001
                redir /photon /photon/

                redir / /photon
        }

repositories:
  - src: https://github.com/Tina-otoge/photongenic

user_services:
  photon:
    workdir: "{{ repositories_dir }}/photongenic"
    cmd: |
      {{ python_setup }}
      pip install gunicorn
      (python archive.py &)
      SCRIPT_NAME=/photon gunicorn -w 4 webui.app:app -b 127.0.0.1:7001
