- name: loki reset-failed
  command: systemctl --user reset-failed loki.service
  failed_when: false
  listen: loki restart

- name: loki restart
  systemd:
    name: loki
    state: restarted
    scope: user
