on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      service:
        required: false
        type: string
        default: ''
      webhook_msg:
        required: false
        default: ''
        type: string
    secrets:
      user:
        required: true
      host:
        required: true
      login_user:
        required: true
      key:
        required: true
      webhook_url:
        required: false

env:
  WEBHOOK_MSG_DEFAULT: '✅ Deployment of ${{ inputs.app }} is complete.'
  WEBHOOK_URL: ${{ secrets.webhook_url }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Ansible
        uses: actions/checkout@v4
        with:
          repository: Tina-otoge/infra
          ref: master
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -r requirements.txt
      - name: Save SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.key }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Run Ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
        run: |
          ansible-playbook -l ${{ secrets.host }} playbooks/deploy_as.yml \
            -u ${{ secrets.login_user }} \
            -e "deploy_user=${{ secrets.user }}" \
            -e "deploy_git=${{ github.server_url }}/${{ github.repository }}" \
            -e "deploy_version=${{ github.sha }}" \
            -e "deploy_app=${{ inputs.app }}" \
            -e "deploy_service=${{ inputs.service }}" \
      - name: Notify
        if: ${{ env.WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"content\":\"${{ inputs.webhook_msg || env.WEBHOOK_MSG_DEFAULT }}\"}" \
            ${{ env.WEBHOOK_URL }}
